### ISSUE TITLE
cragList Issue #1

### ISSUE THREAD

**Issue by jonatsuji** [jonatsuji/userStories#1]
## Value Proposition

**As a** user

**I need** to see a list of boulder routes and in which area I can find it

**to be able to** get these information about routes in germany

## Description

![userStory1-new](https://user-images.githubusercontent.com/115465230/207032022-ffd74f41-4f2d-4a31-978f-662a363a984d.png)

## Acceptance Criteria

- [x] routes need to be shown in a list
- [x] they need min information of area and grade
- [x] has a header with the logo

## Tasks

(for developers team)

- [x]  create new project with create next-app
- [x]  connect project with github
- [x]  clean up folder
- [x]  create folder structure (pages, components, images, fonts,...)
- [x]  set up global styling (e.g. *box-sizing: border-box)
- [x]  create dummy array for routes
- [x]  create header, main component and implement logo
- [x]  create list component
- [x]  responsive design
- [x]  content is scrollable (vertically only)
- [x]  render list
- [x]  create pull request

**Comment by flipkoehler** [comment]
super User Story wie ich finde und schön dass man direkt die wichtigsten Inhalte sehen kann :) 

Einzige Anregung: Vielleicht kannst du das Design noch so reduzieren, dass man dort nur die Inhalte sieht die nach den AKs auch umgesetzt werden.

**Comment by julialoeschel** [comment]
Hey, 
super first Story. 

I would prefer the image to be in the US be be able to view it faster ;) 
In the scribble I spotted a burger menue, that is not part of this US here. try to scribble only what is part of your story. 

Other thank that :octocat:  👍
