### ISSUE TITLE
cragList issue #2

### ISSUE THREAD

**Issue by jonatsuji** [jonatsuji/userStories#2]
## Value Proposition

**As a** user

**I need** to get a list of areas where each item includes the fitting routes

**to be able to** find routes with their areas

## Description

![userStory 2](https://user-images.githubusercontent.com/115465230/207009894-a90a869b-8f57-4a29-b43e-94a55b779c90.png)

## Acceptance Criteria

- [ ] areas need to be shown in a list (incl. an image)
- [ ] they need information about number of routes, grading scale, name and location.
- [ ] onClick directs to a filtered list of routes

## Tasks

(for developers team)

- [ ]  create "area"-list component
- [ ]  create card design which incl. all information
- [ ]  filter routes for their area and show fitting list in each area
- [ ]  responsive design
- [ ]  content is scrollable (vertically only)
- [ ]  render list
- [ ]  create pull request

**Comment by julialoeschel** [comment]
cool. 
Anmerkungen: 
- brauchen wir hier ein Routing, oder findet das alles noch auf der selben page statt? 
- gerne alle views darstellen, 
   wenn wir hier filtern, sieht die gefilterte Liste sicher anders aus, oder? 
   und es müsste einen "zurück" button geben.
- gibt es einen Filter, der alles in Germay anzeigt, und wäre das für den User interesant? 
- wieder das burgermenu ohne funktion :) gerne raus damit. 

ansonsten ist das ein Sinnvoller 2ter Schritt 👍

**Comment by onebarloop** [comment]
Quite a task, but I'm sure you will manage!
