### ISSUE TITLE
cragList issue #3

### ISSUE THREAD

**Issue by jonatsuji** [jonatsuji/userStories#3]
## Value Proposition

**As a** user

**I need** to see routes filtered in different area "sectors"

**to be able to** navigate myself through a boulderarea

## Description

![userStory3-new](https://user-images.githubusercontent.com/115465230/207038628-006c3028-d4d5-445c-9cea-8b552be31d51.png)

## Acceptance Criteria

- [x] One Area is usually splitted into different sectors. They should be displayed befor the routes
- [x] Sector card shows a few infos about the incl. routes.

## Tasks

(for developers team)

- [x]  create "sector" list component
- [x]  create card design with all sector information incl.
- [x]  onClick will list all routes from this sector (filter())
- [x]  responsive design
- [x]  content is scrollable (vertically only)
- [x]  render list
- [x]  create pull request

**Comment by julialoeschel** [comment]
Hey, 
sieht gut aus. 

ist das eine weitere Seite? nach den Ländern und vor den einzelnen Routen? 
evt fhlt hier noch ein button "zurück", wenn einem die Routen dort zu schwer sind :) 

Der Bookmark button -> ohne Funktion? dann raus (evt ist mir das bei vorherigen US auch entgangen 🙃
