### ISSUE TITLE
cragList issue #4

### ISSUE THREAD

**Issue by jonatsuji** [jonatsuji/userStories#4]
## Value Proposition

**As a** user

**I need** to search for route, area or sector names

**to be able to** find specific information

## Description

![userStory4](https://user-images.githubusercontent.com/115465230/207090919-d820eaba-c767-46b9-94a2-63faa5d82aa9.png)

## Acceptance Criteria

- [x] searchbar should be available in areas, sectors and routes
- [x] results should be shown onChange (immediatly)
- [ ] results should be filtered (to areas, sectors and routes)

## Tasks

(for developers team)

- [x]  create searchbar component
- [x]  write a handleSearch function
- [x]  pass the function to all 3 searchbars on the different pages
- [x]  responsive design for the bar
- [x]  content (results) is scrollable (vertically only)
- [x]  render result-list
- [x]  create pull request
